### PR TITLE
Add an optional 'handlers' section to the config file for special han…

### PR DESCRIPTION
**Pull request by llvtt**
…dling of certain mimetypes.

I can clean this up any way you prefer; I just wanted to gauge interest in this feature first.

**Inspiration**
iTerm (terminal emulator I use on my mac) recently gained the ability to display images directly in the terminal: http://iterm2.com/documentation-images.html. I thought, why not make this available in RTV?

**Configuration**
Something like this goes into your rtv.cfg:

    [handlers]
    ; Special handler to open images.
    ; <handler name> = <list-of-mimetypes>
    rtv.mime_handlers.iterm2_image_viewer = image/jpeg,image/jpg,image/png,image/gif

**Results**

bildschirmfoto 2016-06-12 um 16 59 03
bildschirmfoto 2016-06-12 um 16 58 59

This isn't just about images, though. This allows users to handle different mimetypes with python functions from RTV. I could also imagine a function to handle audio without leaving the terminal, for example. Also, as long as the function is importable, rtv can use it. It doesn't have to be defined in rtv's own source code.

Hope someone else finds this hack interesting/useful. Let me know if you think something needs to be cleaned up/changed.

### CODE REVIEW

**Comment by llvtt** [comment]
I made another commit to fix the existing tests, though I haven't added any for my own code. I'd first like to know if something like this is of interest to the project, and if so, I'd be happy to write tests for it. Just let me know.

**Comment by llvtt** [comment]
D'oh! I just made something I thought was cool and dropped a PR here without looking at the larger context of the project. I see now that this PR more or less duplicates the effort of #223, which is using mailcap. That's a better idea than using the config file like I'm doing here, since it doesn't require writing any code on the user's part and just does the Right Thing if the user has one set up already.

@michael-lazar @Ziul, let me know if either of you need any help working on this. I recently started using RTV and am hooked, and I'd love to contribute something back.

Thanks for the great work!

**Comment by michael-lazar** [comment]
Hi @llvtt, thanks for the PR! This is probably the most requested feature for rtv and there have been at least a half dozen attempts (mostly by me) so far.

I wish I could try it out but unfortunately I don't have access to a mac :cry: The iTerm viewer looks super interesting though, reminds me of something that I saw in [ranger](https://github.com/ranger/ranger/blob/master/ranger/ext/img_display.py#L181). I also like the way that you set up the config file with importable python handlers. If you don't mind, I'd like to re-open this and at least keep it around as a reference that we can pull ideas from.

**Comment by llvtt** [comment]
I definitely don't mind reopening this :).

Using python handlers as I've done here is nice because we can integrate easily with the Terminal object for displaying notifications, among other uses.

However, as I mentioned before, using mailcap is great because the same mailcap file can be used across applications. Using external programs to deal with various mimetypes is also less maintenance work for this project, rather needing to add new python handler functions for each mimetype.

I'd be willing to make this PR use mailcap, but I don't want to step on anyone's toes who's already working on this.

**Comment by michael-lazar** [comment]
Linking to issue https://github.com/michael-lazar/rtv/issues/78 so it shows up on the tracker.

**Comment by michael-lazar** [comment]
The mailcap approach has now been released, so I think it's a good time to close this. Please let me know if you have any suggestions for improving the default mailcap settings for iTerm!

**Pull request closed without merging**
