### PR TITLE
Wrap comments and function docstrings to 72 column

### PR DESCRIPTION
**Pull request by nagracks**

### CODE REVIEW

**Comment by michael-lazar** [comment]
Please read the style guide here https://github.com/michael-lazar/rtv/blob/master/CONTRIBUTING.rst

**Comment by nagracks** [comment]
What's wrong with it? I tried to make it PEP8.

**Comment by michael-lazar** [comment]
I meant the last bullet point

- Please don't submit pull requests for style-only code changes

Very few people actually follow the 72 line doc rule and it would be painful to try to enforce this on every single future pull request. More importantly, it doesn't actually improve readability so I don't see the point.

**Comment by nagracks** [comment]
Okay :)

**Pull request closed without merging**
