### PR TITLE
Readme: it's dnf not yum for fedora 24+

### PR DESCRIPTION
**Pull request by vivekanand1101**
Signed-off-by: Vivek Anand <vivekanand1101@gmail.com>

### CODE REVIEW

**Comment by vivekanand1101** [comment]
It doesn't work for me though :/

**Comment by vivekanand1101** [comment]
screenshot from 2017-10-14 19-11-33

**Comment by vivekanand1101** [comment]
Is it possible it's because of tmux?

**Comment by michael-lazar** [comment]
Thanks, there's currently a problem with the RPM package. See issue https://github.com/michael-lazar/rtv/issues/449.

**Pull request merged**
