### PR TITLE
Parse complete imgur albums

### PR DESCRIPTION
**Pull request by woorst**
Multipage imgur albums can be parsed now.

One thing to note: albums can contain mixed content, e.g. .gifv and .jpg. Not sure what mime type to use for that.

### CODE REVIEW

**Comment by michael-lazar** [comment]
Hey thanks, could you post some examples of imgur links that this fixes so I can add test cases?

**Comment by michael-lazar** [comment]
I was also thinking about mixed content and couldn't come up with a good solution, perhaps it would be best to open those ones with the web browser for now.

**Comment by woorst** [comment]
The `/r/diy` subreddit frequently has large imgur albums, e.g. `https://imgur.com/a/q8Vv4`

**Comment by michael-lazar** [comment]
Looks like it fails for single picture galleries, e.g. http://imgur.com/gallery/0YhKlLr doesn't have a corresponding album.

**Pull request closed without merging**
