### PR TITLE
added a manpage

### PR DESCRIPTION
**Pull request by shaggytwodope**
Added a simple man page, if this is a shit idea. Or you'd like something re-done let me know. 

Most of it is taken from -h output, be glad to redo any bit.

### CODE REVIEW

**Comment by michael-lazar** [comment]
Hey this is great! I'm not too familiar with man pages, is there a guide/example that you went off of when setting up the **setup.py** file? I would love to take a look out of curiosity. Also does this work on both linux and osx?

**Comment by shaggytwodope** [comment]
Python has no native mechanism I'am aware of to handle manpages, Alot of projects simply use the data_files feature in setup.py to do this. I basicly searched all over the web on how to do this. 

One example would be https://github.com/0x90/scapy-osx/blob/master/setup.py

I see no reason not to expect it to work for osx (alot of stuff I googled does this the same). However I've no such hardware to test on, so can't confirm this on my own.

**Comment by shaggytwodope** [comment]
Little bit of googling http://serverfault.com/questions/391834/where-are-os-x-man-pages-stored
Assuming no odd env settings by the user, this should work. However as I mentioned I've no way to confirm. If anyone can confirm this tho as the default path that'd be wonderful.

**Comment by michael-lazar** [comment]
Yea I just checked [youtube-dl](https://github.com/rg3/youtube-dl/blob/master/setup.py) and they do the same thing as well (share/man/man1). It looks like it should work for at least the majority of distros.

**Comment by michael-lazar** [comment]
I'm thinking about removing the "Controls" section. There are quite a few keys and I foresee it becoming a pain to maintain the definitions across 3 different files (readme, docs.py, and now the man page). I think it would be ok to add something like "type ? for a list of commands" to the description section instead. Thoughts?

Also how about adding an ENVIRONMENT section with short descriptions for $RTV_EDITOR and $BROWSER, since those are both used environment variables that we use.

**Comment by michael-lazar** [comment]
Also a FILES section that lists the config file location

**Comment by shaggytwodope** [comment]
https://u.teknik.io/KcYxNP.png
Added the sections you mentioned, tossed a screenshot cause I can. As far as removing the controls part just say the word and I can remove it. Just mention the basics maybe, and then point towards the feature to press ? and view list in rtv. I think thats a nice balance, a man page doesn't need to be utterly details if the program offers some basics for use imo.

As always anything needs to be fixed or something let me know, I'am far from the greatest editor ever lol.

**Comment by michael-lazar** [comment]
Good point. I would say go for it, remove the controls section and replace with a short blurb (a sentence or two) about the basic controls and pressing ``?``. You can get rid of the authentication section too, the master branch has switched to using only OAuth now.

**Comment by shaggytwodope** [comment]
Alrighty, edited accordingly.

**Comment by michael-lazar** [comment]
Merged! I made some minor changes in style, I hope you don't mind.

I also had some fun and turned the manpage into a template. So now when you do something like change the version number or add a new command line argument you can simply run ``python scripts/build_manpage`` and the page will be rebuilt. That way, hopefully it won't fall out-of-date with the rest of the documentation!

**Comment by shaggytwodope** [comment]
No worries at all on any changes. I need to remember to add the new manpage generation to the new release version for the AUR package.

**Comment by michael-lazar** [comment]
As of now you shouldn't have to do anything, I'll run it everytime there's a new release and commit the updated manpage to the master branch.

**Pull request merged**
