### PR TITLE
Number keys to refresh the submission/comments and sort by hot/top/rising/new/controversial

### PR DESCRIPTION
**Pull request by yskmt**
I think it is related to:
https://github.com/michael-lazar/rtv/pull/11 and https://github.com/michael-lazar/rtv/pull/13

Keys:
1: hot, 2: top, 3: rising, 4: new, 5: controversial

The header shows the sorting method next to title

I also added `praw.errors.NotFound` in `SubredditContent.__init__` so this issue https://github.com/michael-lazar/rtv/issues/80 should be fixed too.

### CODE REVIEW

**Comment by yskmt** [comment]
As I am submitting this PL, I realized that some subreddit has only a few sorting methods, and choosing the non-existing sorting method crashes the app (e.g. [/r/haskell](https://www.reddit.com/r/haskell)). That needs to be fixed...

**Comment by michael-lazar** [comment]
Thanks, I'll look over it this weekend

**Comment by michael-lazar** [comment]
Looks good! I went ahead refactored a few small things that I saw. I changed the header from ``python : new`` to ``python [new]`` because I think it looks a bit cleaner. I also hijacked this PR to fix a couple of bugs I found with the sorting order in general. Try it out when you get the chance and let me know if I broke anything :smile: 

As always thanks for the PR. :+1: We should add this to the documentation before the next release goes out.

**Comment by yskmt** [comment]
Thanks, I didn't realize that I just have to edit `BasePage` class for common functionality :sweat_smile:

**Pull request merged**
